apiVersion: v1
kind: Pod
metadata:
  name: binance-bot-listener-worker
spec:
  containers:
  - name: binance-bot-listener-worker
    image: eu.gcr.io/rtstockmarkets/binance-bot-listener:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: 0.1
      limits:
        memory: "128Mi"
        cpu: 0.2
    env:
    - name: GC_CREDENTIALS_PATH
      value: /secrets/credentials.json
    - name: API_KEY
      value: aPK7BWKImxGmqZsiuGv05JK1Mz0VYutavvWqaQ4CY1XJX5bnIi40in2ZOUYBKcKv
    - name: SECRET_KEY
      value: 00oaTyCCKG5SZ3rt2332udmuFKoQP9U5aHpV5ED4rrNxWs0Jbp8ybb1LZxxqnocy
    - name: EXCHANGE
      value: binance-futures
    - name: PAIRS_TOPIC
      value: pair-announced-binance
    volumeMounts:
    - name: credentials
      mountPath: /secrets/
      readOnly: true
  volumes:
  - name: credentials
    secret:
      secretName: pub-sub-credentials